export const posts = [
  {
    id: "article-one",
    img: "images/blog_images/blogOne.avif",
    alt: "image information",
    date: "Apr22,2023",
    title: "Blog One",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id minima magnam blanditiis saepe consequatur reiciendis, numquam magni fuga. Temporibus exercitationem deserunt nobis ratione, iure aut quasi dolor modi ea harum!",
  },
  {
    id: "article-two",
    img: "images/blog_images/blogTwo.avif",
    alt: "image information",
    date: "Apr22,2023",
    title: "Blog Two",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id minimadfghh magnam blanditiis saepe consequatur reiciendis, numquam magni fuga. Temporibus exercitationem deserunt nobis ratione, iure aut quasi dolor modi ea harum!",
  },
  {
    id: "article-three",
    img: "images/blog_images/blogThree.avif",
    alt: "image information",
    date: "Apr22,2023",
    title: "Blog Three",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id minima magnam blanditiis saepe consequatur reiciendis, numquam magni fuga. Temporibus exercitationem deserunt nobis ratione, iure aut quasi dolor modi ea harum!",
  },
  {
    id: "article-four",
    img: "images/blog_images/blogFour.avif",
    alt: "image information",
    date: "Apr22,2023",
    title: "Blog Four",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id minima magnam blanditiis saepe consequatur reiciendis, numquam magni fuga. Temporibus exercitationem deserunt nobis ratione, iure aut quasi dolor modi ea harum!",
  },
  {
    id: "article-five",
    img: "images/blog_images/blogFive.avif",
    alt: "image information",
    date: "Apr22,2023",
    title: "Blog Five",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id minima magnam blanditiis saepe consequatur reiciendis, numquam magni fuga. Temporibus exercitationem deserunt nobis ratione, iure aut quasi dolor modi ea harum!",
  },
  {
    id: "article-six",
    img: "images/blog_images/blogSix.avif",
    alt: "image information",
    date: "Apr22,2023",
    title: "Blog Six",
    body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id minima magnam blanditiis saepe consequatur reiciendis, numquam magni fuga. Temporibus exercitationem deserunt nobis ratione, iure aut quasi dolor modi ea harum!",
  },
];
